import SwiftUI
import UIKit

// MARK: - Share sheet wrapper

struct ActivityView: UIViewControllerRepresentable {
    let items: [Any]
    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: items, applicationActivities: nil)
    }
    func updateUIViewController(_ vc: UIActivityViewController, context: Context) {}
}

// MARK: - Simple sparkline for the report (Canvas renders cleanly into PDF)

struct ReportSparkline: View {
    let values: [Int]
    let color: Color
    var body: some View {
        Canvas { ctx, size in
            guard values.count > 1 else { return }
            let minV = Double(values.min() ?? 0)
            let maxV = Double(values.max() ?? 1)
            let range = max(maxV - minV, 1)
            var path = Path()
            for (i, v) in values.enumerated() {
                let x = size.width * CGFloat(i) / CGFloat(values.count - 1)
                let y = size.height - CGFloat((Double(v) - minV) / range) * size.height
                if i == 0 { path.move(to: CGPoint(x: x, y: y)) }
                else { path.addLine(to: CGPoint(x: x, y: y)) }
            }
            ctx.stroke(path, with: .color(color), style: StrokeStyle(lineWidth: 2, lineJoin: .round))
        }
        .frame(height: 60)
    }
}

// MARK: - The printable report (light theme for PDF)

struct ReportView: View {
    let vm: WorkoutViewModel
    let store: WorkoutStore

    private let ink = Color.black
    private let muted = Color(white: 0.45)
    private let accent = Color(red: 0.85, green: 0.20, blue: 0.22)

    private var weightLbs: Int { Int((vm.weightKg / 0.453592).rounded()) }

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            // Header
            VStack(alignment: .leading, spacing: 2) {
                Text("Zone Alert — Data Export").font(.system(size: 22, weight: .bold))
                Text("Generated \(Date().formatted(date: .abbreviated, time: .shortened)) · v\(AppInfo.version)")
                    .font(.system(size: 11)).foregroundColor(muted)
            }

            sectionTitle("Profile")
            grid([
                ("Age", "\(vm.age) yrs"),
                ("Sex", vm.isMale ? "Male" : "Female"),
                ("Weight", "\(weightLbs) lbs"),
                ("Max HR", "\(vm.mhr) bpm (\(vm.usingMeasuredMax ? "measured" : "220 − age"))"),
                ("Resting HR", "\(vm.restingHR) bpm"),
                ("VO₂ Max (est.)", String(format: "%.1f ml/kg/min", vm.vo2maxEstimate(usingMax: vm.mhr))),
            ])

            sectionTitle("Alert band")
            grid([
                ("Method", vm.useHRR ? "Heart-Rate Reserve" : "% of Max HR"),
                ("Target zone", "Zone \(vm.bandZone)"),
                ("Don't drop below", "\(vm.floorBpm) bpm"),
                ("Don't exceed", "\(vm.ceilingBpm) bpm"),
            ])

            trendSection("Resting HR trend", series: store.series("resting"), color: .green)
            trendSection("Aerobic threshold trend", series: store.series("ownzone"), color: accent)

            sectionTitle("Workouts (\(store.records.count) total)")
            workoutTable

            Text("Generated by Zone Alert. Heart-rate training aid, not a medical device.")
                .font(.system(size: 9)).foregroundColor(muted).padding(.top, 6)
        }
        .padding(36)
        .frame(width: 612, alignment: .leading)
        .background(Color.white)
        .foregroundColor(ink)
    }

    private func sectionTitle(_ t: String) -> some View {
        Text(t).font(.system(size: 15, weight: .bold)).foregroundColor(accent)
            .padding(.top, 6)
    }

    private func grid(_ items: [(String, String)]) -> some View {
        VStack(spacing: 4) {
            ForEach(items.indices, id: \.self) { i in
                HStack {
                    Text(items[i].0).font(.system(size: 12)).foregroundColor(muted)
                    Spacer()
                    Text(items[i].1).font(.system(size: 12, weight: .semibold))
                }
            }
        }
    }

    @ViewBuilder
    private func trendSection(_ title: String, series: [Measurement], color: Color) -> some View {
        if !series.isEmpty {
            sectionTitle(title)
            let vals = series.map { $0.bpm }
            if vals.count > 1 { ReportSparkline(values: vals, color: color) }
            VStack(spacing: 3) {
                ForEach(series.suffix(15).reversed()) { m in
                    HStack {
                        Text(m.date.formatted(date: .abbreviated, time: .shortened))
                            .font(.system(size: 11)).foregroundColor(muted)
                        Spacer()
                        Text("\(m.bpm) bpm").font(.system(size: 11, weight: .semibold))
                    }
                }
            }
        }
    }

    private var workoutTable: some View {
        VStack(spacing: 4) {
            HStack {
                cell("Date", 150, .leading, bold: true)
                cell("Time", 70, .trailing, bold: true)
                cell("Dist", 60, .trailing, bold: true)
                cell("kcal", 50, .trailing, bold: true)
                cell("Avg", 50, .trailing, bold: true)
                cell("Peak", 50, .trailing, bold: true)
            }
            Divider()
            ForEach(store.records.prefix(40)) { r in
                HStack {
                    cell(r.date.formatted(date: .abbreviated, time: .shortened), 150, .leading)
                    cell(WorkoutViewModel.clock(r.duration), 70, .trailing)
                    cell(String(format: "%.2f", r.distanceMiles), 60, .trailing)
                    cell("\(Int(r.calories))", 50, .trailing)
                    cell("\(r.avgBpm)", 50, .trailing)
                    cell("\(r.peakBpm)", 50, .trailing)
                }
            }
            if store.records.isEmpty {
                Text("No workouts saved yet.").font(.system(size: 11)).foregroundColor(muted)
            }
        }
    }

    private func cell(_ t: String, _ w: CGFloat, _ align: Alignment, bold: Bool = false) -> some View {
        Text(t)
            .font(.system(size: 11, weight: bold ? .bold : .regular))
            .frame(width: w, alignment: align)
    }
}

// MARK: - PDF generation

enum PDFExport {
    @MainActor
    static func generate(vm: WorkoutViewModel, store: WorkoutStore) -> URL? {
        let renderer = ImageRenderer(content: ReportView(vm: vm, store: store))
        renderer.proposedSize = ProposedViewSize(width: 612, height: nil)

        let url = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("ZoneAlert-Export.pdf")

        var produced = false
        renderer.render { size, renderInContext in
            var box = CGRect(x: 0, y: 0, width: size.width, height: size.height)
            guard let pdf = CGContext(url as CFURL, mediaBox: &box, nil) else { return }
            pdf.beginPDFPage(nil)
            renderInContext(pdf)
            pdf.endPDFPage()
            pdf.closePDF()
            produced = true
        }
        return produced ? url : nil
    }
}
