import SwiftUI
import UIKit

// MARK: - Share sheet wrapper

struct ActivityView: UIViewControllerRepresentable {
    let items: [Any]
    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: items, applicationActivities: nil)
    }
    func updateUIViewController(_ vc: UIActivityViewController, context: Context) {}
}

// MARK: - Simple sparkline for the report (Canvas renders cleanly into PDF)

struct ReportSparkline: View {
    let values: [Int]
    let color: Color
    var body: some View {
        Canvas { ctx, size in
            guard values.count > 1 else { return }
            let minV = Double(values.min() ?? 0)
            let maxV = Double(values.max() ?? 1)
            let range = max(maxV - minV, 1)
            var path = Path()
            for (i, v) in values.enumerated() {
                let x = size.width * CGFloat(i) / CGFloat(values.count - 1)
                let y = size.height - CGFloat((Double(v) - minV) / range) * size.height
                if i == 0 { path.move(to: CGPoint(x: x, y: y)) }
                else { path.addLine(to: CGPoint(x: x, y: y)) }
            }
            ctx.stroke(path, with: .color(color), style: StrokeStyle(lineWidth: 2, lineJoin: .round))
        }
        .frame(height: 60)
    }
}

// MARK: - Shared report styling

private let ink = Color.black
private let muted = Color(white: 0.45)
private let accent = Color(red: 0.85, green: 0.20, blue: 0.22)

private func sectionTitle(_ t: String) -> some View {
    Text(t).font(.system(size: 15, weight: .bold)).foregroundColor(accent).padding(.top, 6)
}

// MARK: - Page 1: the readable, visual report

struct ReportView: View {
    let vm: WorkoutViewModel
    let store: WorkoutStore
    let weightStore: WeightStore

    private var weightLbs: Int { Int((vm.weightKg / 0.453592).rounded()) }
    private func zoneBounds(_ z: Int) -> (Int, Int) {
        vm.useHRR
            ? (Zones.lowerBpmHRR(zone: z, mhr: vm.mhr, rest: vm.restingHR),
               Zones.upperBpmHRR(zone: z, mhr: vm.mhr, rest: vm.restingHR))
            : (Zones.lowerBpm(zone: z, mhr: vm.mhr), Zones.upperBpm(zone: z, mhr: vm.mhr))
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            VStack(alignment: .leading, spacing: 2) {
                Text("Zone Alert — Data Export").font(.system(size: 22, weight: .bold))
                Text("Generated \(Date().formatted(date: .abbreviated, time: .shortened)) · v\(AppInfo.version)")
                    .font(.system(size: 11)).foregroundColor(muted)
            }

            sectionTitle("Profile")
            grid([
                ("Age", "\(vm.age) yrs"),
                ("Sex", vm.isMale ? "Male" : "Female"),
                ("Weight", "\(weightLbs) lbs"),
                ("Max HR", "\(vm.mhr) bpm (\(vm.usingMeasuredMax ? "measured" : "220 − age"))"),
                ("Resting HR", "\(vm.restingHR) bpm"),
                ("VO₂ Max (est.)", String(format: "%.1f ml/kg/min", vm.vo2maxEstimate(usingMax: vm.mhr))),
            ])

            sectionTitle("Zones (\(vm.useHRR ? "Heart-Rate Reserve" : "% of Max HR"))")
            VStack(spacing: 3) {
                ForEach(Array((1...5).reversed()), id: \.self) { z in
                    let b = zoneBounds(z)
                    HStack {
                        Text("Zone \(z) · \(Zones.all[z - 1].name)").font(.system(size: 12)).foregroundColor(muted)
                        Spacer()
                        Text("\(b.0)–\(b.1) bpm").font(.system(size: 12, weight: .semibold))
                    }
                }
            }

            sectionTitle("Alert band")
            grid([
                ("Target zone", "Zone \(vm.bandZone)"),
                ("Don't drop below", "\(vm.floorBpm) bpm"),
                ("Don't exceed", "\(vm.ceilingBpm) bpm"),
            ])

            trendSection("Resting HR trend", series: store.series("resting"), color: .green)
            trendSection("Aerobic threshold trend", series: store.series("ownzone"), color: accent)
            trendSection("HR recovery trend", series: store.series("recovery"), color: .blue)

            weightSummary

            sectionTitle("Recent workouts (\(store.records.count) total)")
            workoutTable(store.records.prefix(12))

            Text("Generated by Zone Alert. Heart-rate training aid, not a medical device. Raw flat numbers on the next page.")
                .font(.system(size: 9)).foregroundColor(muted).padding(.top, 6)
        }
        .padding(36)
        .frame(width: 612, alignment: .leading)
        .background(Color.white)
        .foregroundColor(ink)
    }

    @ViewBuilder private var weightSummary: some View {
        if !weightStore.weights.isEmpty || !weightStore.days.isEmpty {
            sectionTitle("Weight & calories")
            let vals = weightStore.weights.map { Int($0.lb.rounded()) }
            if vals.count > 1 { ReportSparkline(values: vals, color: .purple) }
            grid([
                ("Latest weight", weightStore.latestWeight.map { String(format: "%.1f lb", $0) } ?? "—"),
                ("Weigh-ins logged", "\(weightStore.weights.count)"),
                ("Days logged (calories)", "\(weightStore.days.filter { $0.eaten > 0 || $0.burned > 0 }.count)"),
            ])
        }
    }

    private func grid(_ items: [(String, String)]) -> some View {
        VStack(spacing: 4) {
            ForEach(items.indices, id: \.self) { i in
                HStack {
                    Text(items[i].0).font(.system(size: 12)).foregroundColor(muted)
                    Spacer()
                    Text(items[i].1).font(.system(size: 12, weight: .semibold))
                }
            }
        }
    }

    @ViewBuilder
    private func trendSection(_ title: String, series: [Measurement], color: Color) -> some View {
        if !series.isEmpty {
            sectionTitle(title)
            let vals = series.map { $0.bpm }
            if vals.count > 1 { ReportSparkline(values: vals, color: color) }
            VStack(spacing: 3) {
                ForEach(series.suffix(8).reversed()) { m in
                    HStack {
                        Text(m.date.formatted(date: .abbreviated, time: .shortened))
                            .font(.system(size: 11)).foregroundColor(muted)
                        Spacer()
                        Text("\(m.bpm) bpm").font(.system(size: 11, weight: .semibold))
                    }
                }
            }
        }
    }

    private func workoutTable<S: Sequence>(_ records: S) -> some View where S.Element == WorkoutRecord {
        VStack(spacing: 4) {
            HStack {
                cell("Date", 150, .leading, bold: true)
                cell("Time", 70, .trailing, bold: true)
                cell("Dist", 60, .trailing, bold: true)
                cell("kcal", 50, .trailing, bold: true)
                cell("Avg", 50, .trailing, bold: true)
                cell("Peak", 50, .trailing, bold: true)
            }
            Divider()
            ForEach(Array(records)) { r in
                HStack {
                    cell(r.date.formatted(date: .abbreviated, time: .shortened), 150, .leading)
                    cell(WorkoutViewModel.clock(r.duration), 70, .trailing)
                    cell(String(format: "%.2f", r.distanceMiles), 60, .trailing)
                    cell("\(Int(r.calories))", 50, .trailing)
                    cell("\(r.avgBpm)", 50, .trailing)
                    cell("\(r.peakBpm)", 50, .trailing)
                }
            }
            if store.records.isEmpty {
                Text("No workouts saved yet.").font(.system(size: 11)).foregroundColor(muted)
            }
        }
    }

    private func cell(_ t: String, _ w: CGFloat, _ align: Alignment, bold: Bool = false) -> some View {
        Text(t).font(.system(size: 11, weight: bold ? .bold : .regular)).frame(width: w, alignment: align)
    }
}

// MARK: - Page 2: hard, flat numbers (everything, plainly)

struct RawNumbersView: View {
    let vm: WorkoutViewModel
    let store: WorkoutStore
    let weightStore: WeightStore

    private let mono = Font.system(size: 9, design: .monospaced)

    var body: some View {
        VStack(alignment: .leading, spacing: 14) {
            Text("Raw Numbers").font(.system(size: 20, weight: .bold))

            sectionTitle("All workouts (\(store.records.count))")
            lines(["date,duration_s,miles,kcal,avg_bpm,peak_bpm,z1_s,z2_s,z3_s,z4_s,z5_s"] +
                  store.records.map { r in
                    let tz = (1...5).map { String(format: "%.0f", $0 < r.timeInZone.count ? r.timeInZone[$0] : 0) }.joined(separator: ",")
                    return "\(r.date.formatted(date: .numeric, time: .shortened)),\(Int(r.duration)),\(String(format: "%.2f", r.distanceMiles)),\(Int(r.calories)),\(r.avgBpm),\(r.peakBpm),\(tz)"
                  })

            sectionTitle("All measurements (\(store.measurements.count))")
            lines(["date,kind,bpm"] +
                  store.measurements.map { "\($0.date.formatted(date: .numeric, time: .shortened)),\($0.kind),\($0.bpm)" })

            sectionTitle("Weight log (\(weightStore.weights.count))")
            lines(["date,lb"] +
                  weightStore.weights.map { "\($0.date.formatted(date: .numeric, time: .shortened)),\(String(format: "%.1f", $0.lb))" })

            sectionTitle("Daily calories (\(weightStore.days.count))")
            lines(["date,burned,eaten,deficit"] +
                  weightStore.days.map { "\($0.dateKey),\($0.burned),\($0.eaten),\($0.burned - $0.eaten)" })
        }
        .padding(36)
        .frame(width: 612, alignment: .leading)
        .background(Color.white)
        .foregroundColor(ink)
    }

    private func lines(_ rows: [String]) -> some View {
        VStack(alignment: .leading, spacing: 1) {
            ForEach(rows.indices, id: \.self) { i in
                Text(rows[i]).font(mono).foregroundColor(i == 0 ? accent : ink)
            }
            if rows.count <= 1 { Text("(none)").font(mono).foregroundColor(muted) }
        }
    }
}

// MARK: - Export: 2-page PDF + raw threshold CSVs

enum ZoneExport {
    @MainActor
    static func generate(vm: WorkoutViewModel, store: WorkoutStore, weightStore: WeightStore) -> [URL] {
        var urls: [URL] = []
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        let pdfURL = docs.appendingPathComponent("ZoneAlert-Report.pdf")
        let pages: [AnyView] = [
            AnyView(ReportView(vm: vm, store: store, weightStore: weightStore)),
            AnyView(RawNumbersView(vm: vm, store: store, weightStore: weightStore)),
        ]
        if renderPDF(pages: pages, to: pdfURL) { urls.append(pdfURL) }
        if vm.ownzoneHasData { urls += vm.ownzoneExportURLs() }   // raw per-second threshold CSVs
        return urls
    }

    @MainActor
    private static func renderPDF(pages: [AnyView], to url: URL) -> Bool {
        var defaultBox = CGRect(x: 0, y: 0, width: 612, height: 792)
        guard let pdf = CGContext(url as CFURL, mediaBox: &defaultBox, nil) else { return false }
        var produced = false
        for page in pages {
            let renderer = ImageRenderer(content: page)
            renderer.proposedSize = ProposedViewSize(width: 612, height: nil)
            renderer.render { size, renderInContext in
                var box = CGRect(x: 0, y: 0, width: size.width, height: max(size.height, 1))
                let boxData = Data(bytes: &box, count: MemoryLayout<CGRect>.size) as CFData
                let info = [kCGPDFContextMediaBox as String: boxData] as CFDictionary
                pdf.beginPDFPage(info)
                renderInContext(pdf)
                pdf.endPDFPage()
                produced = true
            }
        }
        pdf.closePDF()
        return produced
    }
}
